### ISSUE TITLE
Limit the number of projects and publications shown in the authors personal pages

### ISSUE THREAD

**Issue by jgidi** [jgidi/webpage-plasmas-udec#9]
Currently, author pages list all of the projects and publications of the author, thus rendering an awkwardly large page.

A better behavior would be to show the 5 most recent items, and a link to another page containing all projects or publications from that author. This link could also point to all of the projects or publications of the site, since those pages are provided with a search bar to allow further filtering.

**Comment by rnavarromal** [comment]
I would show the 5 most recent publications, and also the current projects.
As for the link containing the author's items, reuse the same folder but filtered by author, e.g. webpage/contents/publications?search=rnavarro (or any other way that accomplishes the same result). This way we avoid the duplication of pages I think.

**Comment by jgidi** [comment]
Totally agree with showing 5 most recent publications + current projects, but this raises the separate issue of establishing time ranges for the projects. I'll open another issue addressing this.

About passing parameters from the url to the search query, I don't currently know how to implement it but I know it must be done in javascript. Also, I guess that a good way to address it would be to make a special page for url-directed searches, as to avoid augmenting the complexity of the existing layouts.

**Comment by jgidi** [comment]
Closing issue in favor PR #11
